import os
import sys

# Insert the project path so Sphinx can import the Franko module
sys.path.insert(0, os.path.abspath('../../Franko'))


def get_version():
    """
    Read the __version__ string from the Franko package init file.
    Raises:
        RuntimeError: if the version string is not found.
    Returns:
        str: the project version
    """
    version_file = os.path.join(os.path.dirname(__file__), '..', '..', 'Franko', '__init__.py')
    with open(version_file, 'r', encoding='utf-8') as f:
        for line in f:
            if line.startswith("__version__"):
                return line.split('=')[1].strip().strip('"\'"')
    raise RuntimeError("Unable to find version string in __init__.py.")


# Project information
project = 'Franko'
author = 'TheDaniell'
release = get_version()

# Sphinx extensions for documentation generation
extensions = [
    'sphinx.ext.napoleon',        # support for Google- and NumPy-style docstrings
    'sphinx.ext.autodoc',         # include docstrings from code
    'sphinx.ext.viewcode',        # add links to highlighted source code
    'sphinx.ext.autosummary',     # generate summary tables for modules/classes/functions
    'sphinx_copybutton',          # add a copy button to code blocks
    'sphinx_toggleprompt',        # add a toggle prompt button to code blocks
    'sphinx_automodapi.automodapi'  # automatically document modules and classes
]

# Napoleon settings
napoleon_include_private_with_doc = True
napoleon_include_private = True

# Autodoc settings
autodoc_default_options = {
    'members': True,
    'undoc-members': True,
    'private-members': True,
}
autodoc_typehints = 'description'

# Autosummary settings
autosummary_generate = True

# TogglePrompt settings
toggleprompt_offset_right = 35

# Prevent showing Sphinx version in footer
html_show_sphinx = False

# Source file suffix and master doc
source_suffix = ['.rst']
master_doc = 'index'

# Language for autogenerated content
language = 'uk_UA'

# Templates and static paths
templates_path = ['_templates']
exclude_patterns = []

# Theme configuration
html_theme = 'sphinx_rtd_theme'
html_static_path = ['_static']
html_theme_options = {
    'style_nav_header_background': '#2980B9',
    'logo_only': False,
    'display_version': True,
}

# Show the copyright and disable source link
html_show_copyright = True
html_show_sourcelink = False
